### ISSUE TITLE
Demo of Passport permit solution

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-residential-parking-permits#69] opened 2019-05-29 02:50 UTC
**Objective** 
ATD currently uses [Passport](https://www.passportparking.com/) for metered parking. The platform has a permit solution that we want to evaluate for RPP. 
 - [City of Oak Park, IL RPP Landing Page](https://oakpark.cmrpay.com/permits/login)
 - [Case studies](https://www.passportinc.com/case-studies/?fwp_products=permits)

**Questions**
- Can we determine eligibility via an address rather than have a customer look it up in a list (as in the Oak Park app) 
- How can residents who don't have a bank/checks or credit card make payments? 
- How will this meet our other permitting needs? 
- (Overview of general API and integration capabilities)

**Invites**
Teri, Amenity, Alyse, Ryan, Joseph, Jacob, John, Diana, Tracy, Peggy

------
- [x] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues

**Comment by amenity** [comment] 2019-06-06 20:05
Passport Call 6/6

Teri, John, Amenity, Diana, Ryan, Alyse, Jacob, Jason

Curtis - Passport

### Notes

- Just acquired Complus - parking enforcement
- Typically 30% of application is custom based on various customer needs, e.g. 10k accounts for NYC Housing Authority, Virginia Beach beach permits, LA County Metro Rail transit rider verification permits
- Cloud-hosted
- Can send renewal emails out in bulk
- Translation available in mobile pay, will check to see about permit

Review our current process and needs (go digital)

Application:

- Accounts/login -  progressive profiling - minimal amount of information, 4 digit pin can be used in permit or parking portal
- Login dashboard shows purchased permits or where you are in the process of a permit application
- How does the user know what zone they're in? As opposed to selecting from a drop down… (Currently don't have this feature.)
- Upload documents, gets added to shopping cart, purchase, automatic email with either approval or pending status

Backend:

- Can create rules such as eligibility depends on payment of outstanding charges, etc. 
- Can have approval queue, staff accepts permit then the customer comes to buy it. (Customer then has to log back in to purchase.)
- Set up workflows, limits, types, etc. 

Enforcement:

- Everything tied to a license-plate number
- Can integrate with lots of enforcement providers/equipment; City Vigilent so can read plates from vehicle or handheld

Automate synchronizing lease expiration with permit expiration?



API might be able to do stuff - authentication, alternative front end rendering, other permit applications… Will send us docs

- Has an API could use for authentication? Rendering front end with another tool?

**Comment by johnclary** [comment] 2019-06-06 20:19
Teri's notes from 6/6 call:

* Need to explore DIR contracts - Teri to work with Curtis on it 
* Passport purchased Complus data for enforcement.  Passport acquired Newpark.  New additions to platform. 
* Passport 
    * Mobile cashless tolling 
    * deigital permits 
    * LPR 
    * Mobile pay for parking 
    * mobile ticketing 
    * analytics 
    * micro-mobility management (scooters) 
* San Antonio, Baylor, DFW 
* Security:  PCI, PWC security testing, AWS, SOC 2 compliance 
* $1.5B mobile transactions 
* Permits: 
    * Clients 
        * NYC 10,000 permits, Virginia beach 6,000 permits, 
        * 70% off the shelf, 30% customized 
    * Current process 
    * Goal 
        * Offer  RPP via mobile app, real time guest passes 
    * Questions 
        * how fast can changes be made for look and feel? - couple of days - the template is not changed. 
        * how fast can minor changes be made for the site to keep it current with new ordinances. - our team can make minor configuration changes. 
        * Give examples of integrations that you have done with non-passport systems. - parkmobile, civicsmart 
        * how often is the app updated, is there a regular cycle? - often - wouldn't say 
        * integration with ArcGIS online? - will verify 
        * Tie address to zone type - yes 
        * must pay citation before getting new permit - yes 
        * could the purchase be made automatically after approval without going back into the portal - checking 
        * auto notification is available 
        * all can be done in mobile app 
        * LPR - Brazos units does interface, Vigilant interfaces 
        * Does it do Spanish - will verify 
        * Affordable parking program - separate for now.  Gategear interface needed. 
        * Property management process is slightly different. 
        * Owner process is the same. 
        * what happens for owners of multiple properties?  not sure 
        * automatically/Manually set expiration to the end of the lease. 
        * Airbnb example to set expiration to the end of the rental period. 
        * Can resident edit the vehicle type (car rentals, multiple cars) 
        * Single signon - SamL ADFS - will verify 
        * Could you fix ADA issues?  will verify 
        * Request API info - will send 
        * Interface with Knack.com - will verify 
        * Can add new permit types?  Yes  Must consider enforcement 
        * Different level back end users - yes 
        * access to the demo site - will verify 
        * fees - will work out with you  - currently $0.30 same wallet 
        * visa gift - will verify 
        * can mark someone as paid for cash payments - yes

**Comment by dianamartin** [comment] 2019-06-06 20:20
Diana's Notes

Curtis Morgan – Passport 
Digitial Permits Discussion 

Ticket issuance 
License Plate recognition 
Parking Enforcement application 

Works with 1000+ clients 
Security and Compliance – house their data 
65-75% Off the shelf – 30% custom 

**Discovery – Passport Questions** 
- What does the current application process looks like? 
- How are renewals handled? 
- How are permits enforced? 
- What is the estimated approval time? 
- What tasks would you like to see be automated? 
- Guest Passes? 
- In App Permit workflow 

**Smart City demo app** 
Look and feel, can do custom branding 

"Log In – Sign up" 
Content for why you need an account 

Phone 
4 digit pin to enter 

Shows "View Permits" 
Shows "Inactive Permits" 
Test 14-Day Visitor 
See "Approval queue" 
"Pizza 1-2-3" 

 "Add new permit" button 
Shows permits 
"Test Residential Permit" 
"Test Residential Renewal Permit" 
[Purchase] button 

Customer adds Permit Information 
Notified about permit they're purchasing 
Type - "Test Residential Renewal" 
Zone – "Blue Garage" automated? Which zone are you? 
Cycle "Test Renewal Cycle" 
Valid From "06/01/2019 thru 06/30/2019" 
Price - "$66.00" 
Availability - "Available" 

Customer adds Vehicle Information 
License Plate State 
License Plate Number 
Make 
Model 
Color 

Customer adds Customer Information 
First Name 
Last Name 
Address 
City 
State 
Zip Code 
Phone Number 
Email 

Attachments – load documents 
Current Vehicle Registration – load documents 

Pay now 
Enter payment 
"Permit Payment Successful" 

**BACKEND** 
Email of Purchase Summary 
Permit Summary 

**Demo had no approval process** 
RPP Staff – Operator Management 

**MANAGE PERMITS** 
See Permit Details 
See Payment Info 
User Info 
Documents 
Violations – tied to BRAZOS? 
Marks 
Trail – digital trail, audit trail (Ex. Purchased, Email Sent) - touch point of system and customer (time stamped and documented) 
 
**DEMO APPROVAL PROCESS** 
Add New Permit 
Fill in information 
Customer Checks out 
Pays for permit 
Notification "Success" 
Order has been made 
Email Application Summary 
Permit Summary 
Status: "Pending for Approval" 

**BACKEND** 
Permit Approval Queue 
Accept – Decline 

**Customer Portal** 
Approval Accepted, must select "Purchase" to complete process 
Teri's question: After approval, run cc payment instead of customer having to go back in.. 
Payment  
"Payment has been successful" 
"Payment order has been confirmed"  
Slightly confusing – email content/wording 

**FUNCTIONALITY** 
Cloud hosted by Passport 
Can send out renewals – bulk email auto process 

>Jason's question: Hot link from email so customer can go into log in page and process Renewal 
New and Renewal Process: will need approval process 

>Teri's Question: How would enforcement officer know a resident has a license plate? 
Enforcement platform has license plate scanners and integrate with handhelds *9/10 can integrate* 
Genotech cameras run on top of hardware 

>John's Question: Permit app – Spanish language (mobile pay) but (Curtis) needs to confirm 

>Teri's Question: Integrate with ArcGIS Online>
How often does the app update? Software upgrades (30-40 engineers) UI, front/backend 
How fast can it take to change content (Look/Feel)? - Banner, color, change picture (a couple of days) 
Configurable content, mainly (emails, page content) 

>John's question: Distinct workflow for home owners/residents?  
Ryan says No, they're the same. 

>Jacob's questions: Tie permit to permit expiration to a lease?  
NO ANSWER, Need to get back to us. 

>Jason statement: hang tag pass between two cars, not always tied to a vehicle 
Edit the vehicle type 
Customer can change the vehicle in the profile 

>Amenity question: Integration single sign on – utility accounts profile 
Platform has open API 
Connected app, does the API support that? 
Current form isn't fully ADA compliant. 
Asking to share API documentation 

>Teri mentions: 
SAML: Standard Authenticate Integration – APIs use SAML or ADFS. Need to research.  
Non-passport can interface in the last year? GenoTech, Arc Mobile, T2 systems, Duncan, CivicSmart 
Interfaced with Knack.com? Need to research. SAaS, workflow management.  

Other Types of permits other than Parking 
Not out of the box, have to customize 

Taxi cab, valet permits, pedicab, chauffeur permits? 

>Teri question: Different level of user? Can have different access and users.  
Ex. Summer intern, tie rules/procedure 
Dummy, demo site? Double check on that.  
Guest log in to sandbox site 

**Merchant Processing Fees** 
COA would process the fee 
Or Passport would serve as merchant of record 

>Ryan's question: individual wanted to pay by cash only 
So staff can create/issue a permit if they walked in

**Comment by ghost** [comment] 2019-06-13 15:09
Closing issue - further actions are in #74

**Closed as completed by ghost** 2019-06-13 15:09 UTC
Labels: Impact: 4-None, Service: Apps, Service: PM, Type: Meeting, Workgroup: PE, Project: Residential Parking Permits
