### ISSUE TITLE
As a returning user obtaining my annual permit I only need to review my contact info and upload proof of residency and pay to obtain my permits. 

### ISSUE THREAD

**Issue by sortizsh** [cityofaustin/atd-residential-parking-permits#15] opened 2018-06-22 20:30 UTC
As a returning user obtaining my annual permit I only need to review my contact info and upload proof of residency and pay to obtain my permits.

**Comment by dianamartin** [comment] 2019-05-06 15:23
Duplicate of #14

**Closed as completed by dianamartin** 2019-05-06 15:23 UTC
Labels: Workgroup: PE, Duplicate, Project: Residential Parking Permits
