### ISSUE TITLE
DUP: H:  As user, I will receive an automated email when my documents are rejected so that I can know to upload new documents.

### ISSUE THREAD

**Issue by sortizsh** [cityofaustin/atd-residential-parking-permits#9] opened 2018-06-22 20:29 UTC
H:  As user, I will receive an automated email when my documents are rejected so that I can know to upload new documents.

**Comment by dianamartin** [comment] 2019-05-06 14:30
Duplicate of #8

**Closed as completed by dianamartin** 2019-05-06 14:30 UTC
Labels: Workgroup: PE, Duplicate, Project: Residential Parking Permits
